version: '3.9'

services:
  postgres_application:
    container_name: postgres_application
    image: postgres:latest
    shm_size: 128mb
    env_file:
      - ../secrets/database-dev.env
      - postgresql.env
    ports:
      - "5432:5432"
    volumes:
      - application_db_volume:/var/lib/postgresql/data
      - ./relation.sql:/docker-entrypoint-initdb.d/relation.sql
    networks:
      - application
      - monitoring
    restart: unless-stopped

  postgres_keycloak:
    container_name: postgres_keycloak
    image: postgres:latest
    shm_size: 128mb
    env_file:
      - ../secrets/database-dev.env
      - postgresql.env
    expose:
      - 5432
    volumes:
      - keycloak_db_volume:/var/lib/postgresql/data
    networks:
      - keycloak
    restart: unless-stopped

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 3300:8080
    networks:
      - application
      - keycloak
    restart: unless-stopped

  keycloak:
    depends_on: 
      - postgres_keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 3200:8080
    expose:
      - 8080
    env_file:
      - ../secrets/keycloak-dev.env
      - keycloak.env
    command: start-dev --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - keycloak
      - monitoring
    restart: unless-stopped

networks:
  application:
  keycloak:
  monitoring:
    external: true

volumes:
  keycloak_db_volume:
  application_db_volume: